# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20171112_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movie_actor', through='movies.Role', to='movies.Person'),
        ),
    ]
